# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sean/GitRepos/vindauga

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sean/GitRepos/vindauga

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sean/GitRepos/vindauga/CMakeFiles /home/sean/GitRepos/vindauga//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sean/GitRepos/vindauga/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vindauga

# Build rule for target.
vindauga: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vindauga
.PHONY : vindauga

# fast build rule for target.
vindauga/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vindauga.dir/build.make CMakeFiles/vindauga.dir/build
.PHONY : vindauga/fast

src/draw.o: src/draw.c.o
.PHONY : src/draw.o

# target to build an object file
src/draw.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vindauga.dir/build.make CMakeFiles/vindauga.dir/src/draw.c.o
.PHONY : src/draw.c.o

src/draw.i: src/draw.c.i
.PHONY : src/draw.i

# target to preprocess a source file
src/draw.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vindauga.dir/build.make CMakeFiles/vindauga.dir/src/draw.c.i
.PHONY : src/draw.c.i

src/draw.s: src/draw.c.s
.PHONY : src/draw.s

# target to generate assembly for a file
src/draw.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vindauga.dir/build.make CMakeFiles/vindauga.dir/src/draw.c.s
.PHONY : src/draw.c.s

src/init.o: src/init.c.o
.PHONY : src/init.o

# target to build an object file
src/init.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vindauga.dir/build.make CMakeFiles/vindauga.dir/src/init.c.o
.PHONY : src/init.c.o

src/init.i: src/init.c.i
.PHONY : src/init.i

# target to preprocess a source file
src/init.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vindauga.dir/build.make CMakeFiles/vindauga.dir/src/init.c.i
.PHONY : src/init.c.i

src/init.s: src/init.c.s
.PHONY : src/init.s

# target to generate assembly for a file
src/init.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vindauga.dir/build.make CMakeFiles/vindauga.dir/src/init.c.s
.PHONY : src/init.c.s

src/input.o: src/input.c.o
.PHONY : src/input.o

# target to build an object file
src/input.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vindauga.dir/build.make CMakeFiles/vindauga.dir/src/input.c.o
.PHONY : src/input.c.o

src/input.i: src/input.c.i
.PHONY : src/input.i

# target to preprocess a source file
src/input.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vindauga.dir/build.make CMakeFiles/vindauga.dir/src/input.c.i
.PHONY : src/input.c.i

src/input.s: src/input.c.s
.PHONY : src/input.s

# target to generate assembly for a file
src/input.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vindauga.dir/build.make CMakeFiles/vindauga.dir/src/input.c.s
.PHONY : src/input.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vindauga.dir/build.make CMakeFiles/vindauga.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vindauga.dir/build.make CMakeFiles/vindauga.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vindauga.dir/build.make CMakeFiles/vindauga.dir/src/main.c.s
.PHONY : src/main.c.s

src/scene.o: src/scene.c.o
.PHONY : src/scene.o

# target to build an object file
src/scene.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vindauga.dir/build.make CMakeFiles/vindauga.dir/src/scene.c.o
.PHONY : src/scene.c.o

src/scene.i: src/scene.c.i
.PHONY : src/scene.i

# target to preprocess a source file
src/scene.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vindauga.dir/build.make CMakeFiles/vindauga.dir/src/scene.c.i
.PHONY : src/scene.c.i

src/scene.s: src/scene.c.s
.PHONY : src/scene.s

# target to generate assembly for a file
src/scene.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vindauga.dir/build.make CMakeFiles/vindauga.dir/src/scene.c.s
.PHONY : src/scene.c.s

src/sound.o: src/sound.c.o
.PHONY : src/sound.o

# target to build an object file
src/sound.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vindauga.dir/build.make CMakeFiles/vindauga.dir/src/sound.c.o
.PHONY : src/sound.c.o

src/sound.i: src/sound.c.i
.PHONY : src/sound.i

# target to preprocess a source file
src/sound.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vindauga.dir/build.make CMakeFiles/vindauga.dir/src/sound.c.i
.PHONY : src/sound.c.i

src/sound.s: src/sound.c.s
.PHONY : src/sound.s

# target to generate assembly for a file
src/sound.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vindauga.dir/build.make CMakeFiles/vindauga.dir/src/sound.c.s
.PHONY : src/sound.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... vindauga"
	@echo "... src/draw.o"
	@echo "... src/draw.i"
	@echo "... src/draw.s"
	@echo "... src/init.o"
	@echo "... src/init.i"
	@echo "... src/init.s"
	@echo "... src/input.o"
	@echo "... src/input.i"
	@echo "... src/input.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/scene.o"
	@echo "... src/scene.i"
	@echo "... src/scene.s"
	@echo "... src/sound.o"
	@echo "... src/sound.i"
	@echo "... src/sound.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

